apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: frontend
resources:
- namespace.yaml
- sitea-frontend-deployment.yaml
- sitea-frontend-service.yaml
- sitea-frontend-route.yaml
- siteb-frontend-deployment.yaml
- siteb-frontend-service.yaml
- siteb-frontend-route.yaml

