apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backend

resources:
- namespace.yaml
- sitea-backend-deployment.yaml
- sitea-backend-service.yaml
- sitea-backend-route.yaml
- siteb-backend-deployment.yaml
- siteb-backend-service.yaml
- siteb-backend-route.yaml

